# Generated by Django 3.2.2 on 2021-05-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('periode', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('duty', models.CharField(max_length=500)),
            ],
        ),
    ]
